
# vi: set ft=ruby

# This file uses experimental vagrant feature documented here: https://www.vagrantup.com/docs/disks/usage
# (This is to resolve issues with vagrant-disksize plugin not working)
# You need to run it with VAGRANT_EXPERIMENTAL="disks" set in your environment, such as
# VAGRANT_EXPERIMENTAL="disks" vagrant up

Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "scripts/setupLDAP.sh"

  config.vm.define "docker" do |docker|
  config.vm.network :private_network, ip: "192.168.2.30"
    docker.vm.box = "ubuntu/bionic64"
    docker.vm.hostname = "docker"
    docker.vm.provider "virtualbox" do |l|
      l.cpus = 4
      l.memory = "8192"
    end

    #docker.vm.network "forwarded_port", guest: 5000, host: 5000
    docker.vm.disk :disk, size: "10GB", primary: true

    end
  end
