Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "scripts/setupDockerSwarm.sh"

  config.vm.define "primary" do |primary|
  #config.vm.provision "shell", path: "scripts/setupDockerSwarm.sh"
    primary.vm.box = "bento/ubuntu-22.04"
    primary.vm.hostname = "primary"
    primary.vm.network :private_network, ip: "192.168.3.10"
    primary.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = 4
    end
  end

  (1..2).each do |i|
    #config.vm.provision "shell", path: "scripts/setupDockerSwarm.sh"
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = "bento/ubuntu-22.04"
      worker.vm.hostname = "worker#{i}"
      worker.vm.network :private_network, ip: "192.168.3.20#{i}"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "8192"
        vb.cpus = 4
      end
    end
  end
end
