
# vi: set ft=ruby

# This file uses experimental vagrant feature documented here: https://www.vagrantup.com/docs/disks/usage
# (This is to resolve issues with vagrant-disksize plugin not working)
# You need to run it with VAGRANT_EXPERIMENTAL="disks" set in your environment, such as
# VAGRANT_EXPERIMENTAL="disks" vagrant up

Vagrant.configure("2") do |config|

  config.vm.define "centos" do |centos|
  config.vm.network :private_network, ip: "192.168.4.10"
  config.vm.box = "centos/stream8"
    centos.vm.hostname = "testing"
    centos.vm.provider "virtualbox" do |l|
      l.cpus = 4
      l.memory = "8192"
    end
    #centos.vm.network "forwarded_port", guest: 8800, host: 8800
    #centos.vm.network "forwarded_port", guest: 8080, host: 8080
    #centos.vm.network "forwarded_port", guest: 9090, host: 9090
    #centos.vm.disk :disk, size: "200GB", primary: true

  end
end
